# Generated by Django 5.1.15 on 2025-12-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='contenu',
        ),
    ]
